export const SEARCH_ACTIVITIES: string = 'SEARCH_ACTIVITY';
export const SEARCH_ACTIVITIES_ASYNC: string = 'SEARCH_ACTIVITIES_ASYNC';
export const SEARCH_COUNTERPARTIES: string = 'SEARCH_COUNTERPARTIES';
export const SEARCH_COUNTERPARTIES_ASYNC: string = 'SEARCH_COUNTERPARTIES_ASYNC';
export const SEARCH_PRODUCTS: string = 'SEARCH_PRODUCTS';
export const SEARCH_PRODUCTS_ASYNC: string = 'SEARCH_PRODUCTS_ASYNC';
