export const GET_COUNTERPARTIES: string = 'GET_COUNTERPARTIES';
export const SAVE_COUNTERPARTY: string = 'SAVE_COUNTERPARTY';
export const SET_COUNTERPARTIES_TEMP: string = 'SET_COUNTERPARTIES_TEMP';
export const GET_BACKUP_COUNTERPARTIES: string = 'GET_BACKUP_COUNTERPARTIES';
